swagger: '2.0'
info:
  version: '1.0'
  title: Cleanse API
  description: >
    ![logo](https://cleanse.studio/static/images/dark-logo.png "Cleanse.studio")


    **This collection is intended to help utilize the cleanse.studio API**


    If you are not already signed up, please visit for your free developer account [https://cleanse.studio/](https://cleanse.studio/)



    ---
  contact: {}
host: example.com
basePath: /api/v1
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com/api/v1
    scopes: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
tags:
- name: Authentication
- name: Get email lists
- name: Import email list
- name: Delete email list
- name: Delete cleaned email list
- name: Get/Download cleaned list
- name: Clean email list
- name: Clean single email
